# String parameter
name: "dope-training"


# Integer parameter
version: 1

# Boolean parameter
enabled: true

# List parameter
features:
  - feature1
  - feature2
  - feature3

# Nested parameters
database:
  host: "localhost"
  port: 5432
  username: "admin"
  password: "password"

# Null parameter
description: null